# Project information
site_name: "Client Registry Documentation"
site_description: "Technical documentation for the Client Registry"
site_author: "IntraHealth"
site_url: "https://github.com/intrahealth/client-registry-docs"

# Repository
repo_name: "intrahealth/client-registry-docs"
repo_url: "https://github.com/intrahealth/client-registry-docs"

# Copyright
copyright: "Copyright &copy; 2020 IntraHealth International"

# Theme
theme:
  name: "material"
  palette:
    primary: "blue grey"
    accent: "indigo"
  language: "en"
  feature:
    tabs: false
  font:
    text: "Roboto"
    code: "Roboto Mono"

nav:
  - 'index.md'
  - 'gettingstarted.md'
  - User Manual: 
    - 'user/concepts.md'
    - 'user/workflow.md'
    - 'user/architecture.md'
    - 'user/decision_rules.md'
    - 'user/benchmarks.md'
    - 'user/ui.md'
    - 'user/dashboard.md'
    - 'user/resources.md'
  - Implementer Manual:
    - 'impl/roles.md'
    - 'impl/considerations.md'
  - Developer Manual:
    - 'dev/security.md'
    - 'dev/openmrs.md'
    - 'dev/docker.md'
    - 'dev/installation.md'
    - 'dev/installation_full.md'
    - 'dev/queries.md'
    - 'dev/queriespy.md'
    - 'dev/configuration.md'
    - 'dev/configurebenchmarks.md'
    - 'dev/production.md'
    - 'dev/backup.md'
    - 'dev/troubleshooting.md'
    - 'dev/docs.md'
  - 'contributing.md'
  - 'about.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
plugins:
  - search
  - git-revision-date-localized
  - pdf-export:
      combined: true
# theme:
# logo: 'images/logo.png' must be 128x128
# logo:
#   icon: 'menu_book'
