# Project information
site_name: "Client Registry Documentation"
site_description: "Technical documentation for the Client Registry"
site_author: "IntraHealth"
site_url: "https://github.com/intrahealth/client-registry-docs"

# Repository
repo_name: "intrahealth/client-registry-docs"
repo_url: "https://github.com/intrahealth/client-registry-docs"

# Copyright
copyright: "Copyright &copy; 2020 IntraHealth International"

# Theme
theme:
  name: "material"
  palette:
    primary: "blue grey"
    accent: "indigo"
  language: "en"
  feature:
    tabs: false
  font:
    text: "Roboto"
    code: "Roboto Mono"

nav:
  - 'index.md'
  - 'gettingstarted.md'
  - User Manual: 
    - 'workflow.md'
    - 'architecture.md'
    - 'decision_rules.md'
    - 'benchmarks.md'
    - 'ui.md'
    - 'dashboard.md'
    - 'resources.md'
  - Developer Manual:
    - 'security.md'
    - 'openmrs.md'
    - 'docker.md'
    - 'installation.md'
    - 'installation_full.md'
    - 'queries.md'
    - 'queriespy.md'
    - 'configuration.md'
    - 'configurebenchmarks.md'
    - 'production.md'
    - 'backup.md'
    - 'troubleshooting.md'
    - 'docs.md'
  - 'contributing.md'
  - 'about.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
plugins:
  - search
  - git-revision-date-localized
  - pdf-export:
      combined: true
# theme:
# logo: 'images/logo.png' must be 128x128
# logo:
#   icon: 'menu_book'
